### ISSUE TITLE
/projects endpoint not working

### ISSUE THREAD

**Issue by kalpitjain0407** [Tiledesk/tiledesk-server#19]
I am installing tiledesk via source code. But when I sign up, a network to /projects is returning 500 status code and sign up stucks there. Not able to find the bug in source code.

**Comment by andrealeo83** [comment]
can you paste the log?

**Comment by kalpitjain0407** [comment]
warn: Problem getting project with id: projects
error: uncaughtException: obj.toObject is not a function
TypeError: obj.toObject is not a function
at clone (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:47:16)
    at EmbeddedDocument.Document.$toObject (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js:3010:13)
    at EmbeddedDocument.Document.toObject (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js:3204:15)
    at clone (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:47:16)
    at cloneArray (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:132:14)
    at clone (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:35:12)
    at cloneObject (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:114:17)
    at clone (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:53:16)
    at model.Document.$toObject (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js:3010:13)
    at model.Document.toObject (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js:3204:15)
    at model.Model.$__handleSave (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/model.js:258:22)
    at model.Model.$__save (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/model.js:337:8)
    at /home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/kareem/index.js:278:20
    at _next (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/kareem/index.js:102:16)
    at process.nextTick (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/kareem/index.js:507:38)
    at processTicksAndRejections (internal/process/next_tick.js:74:9) {"error":{},"stack":"TypeError: obj.toObject is not a function\n    at clone (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:47:16)\n    at EmbeddedDocument.Document.$toObject (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js:3010:13)\n    at EmbeddedDocument.Document.toObject (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js:3204:15)\n    at clone (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:47:16)\n    at cloneArray (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:132:14)\n    at clone (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:35:12)\n    at cloneObject (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:114:17)\n    at clone (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js:53:16)\n    at model.Document.$toObject (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js:3010:13)\n    at model.Document.toObject (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js:3204:15)\n    at model.Model.$__handleSave (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/model.js:258:22)\n    at model.Model.$__save (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/model.js:337:8)\n    at /home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/kareem/index.js:278:20\n    at _next (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/kareem/index.js:102:16)\n    at process.nextTick (/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/kareem/index.js:507:38)\n    at processTicksAndRejections (internal/process/next_tick.js:74:9)","exception":true,"date":"Tue Mar 17 2020 17:29:34 GMT+0530 (India Standard Time)","process":{"pid":32482,"uid":1000,"gid":1000,"cwd":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master","execPath":"/usr/local/bin/node","version":"v11.10.0","argv":["/usr/local/bin/node","/home/kalpit/Desktop/tiledesk/tiledesk-server-master/bin/www"],"memoryUsage":{"rss":89886720,"heapTotal":49025024,"heapUsed":42293312,"external":18306455}},"os":{"loadavg":[3.5732421875,2.83984375,2.72216796875],"uptime":17253},"trace":[{"column":16,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js","function":"clone","line":47,"method":null,"native":false},{"column":13,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js","function":"EmbeddedDocument.Document.$toObject","line":3010,"method":"$toObject","native":false},{"column":15,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js","function":"EmbeddedDocument.Document.toObject","line":3204,"method":"toObject","native":false},{"column":16,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js","function":"clone","line":47,"method":null,"native":false},{"column":14,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js","function":"cloneArray","line":132,"method":null,"native":false},{"column":12,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js","function":"clone","line":35,"method":null,"native":false},{"column":17,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js","function":"cloneObject","line":114,"method":null,"native":false},{"column":16,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/helpers/clone.js","function":"clone","line":53,"method":null,"native":false},{"column":13,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js","function":"model.Document.$toObject","line":3010,"method":"$toObject","native":false},{"column":15,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/document.js","function":"model.Document.toObject","line":3204,"method":"toObject","native":false},{"column":22,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/model.js","function":"model.Model.$__handleSave","line":258,"method":"$__handleSave","native":false},{"column":8,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/mongoose/lib/model.js","function":"model.Model.$__save","line":337,"method":"$__save","native":false},{"column":20,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/kareem/index.js","function":null,"line":278,"method":null,"native":false},{"column":16,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/kareem/index.js","function":"_next","line":102,"method":null,"native":false},{"column":38,"file":"/home/kalpit/Desktop/tiledesk/tiledesk-server-master/node_modules/kareem/index.js","function":"process.nextTick","line":507,"method":"nextTick","native":false},{"column":9,"file":"internal/process/next_tick.js","function":"processTicksAndRejections","line":74,"method":null,"native":false}]}

**Comment by mibrahim-cequens** [comment]
@kalpitjain0407 , @andrealeo83 we got the same error when creating a new project Please advise what we should do?


`obj.toObject is not a function
TypeError: obj.toObject is not a function
    at clone (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/helpers/clone.js:47:16)
    at EmbeddedDocument.Document.$toObject (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/document.js:3053:13)
    at EmbeddedDocument.Document.toObject (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/document.js:3249:15)
    at clone (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/helpers/clone.js:47:16)
    at cloneArray (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/helpers/clone.js:133:14)
    at clone (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/helpers/clone.js:35:12)
    at cloneObject (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/helpers/clone.js:114:17)
    at clone (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/helpers/clone.js:53:16)
    at model.Document.$toObject (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/document.js:3053:13)
    at model.Document.toObject (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/document.js:3249:15)
    at model.Document.inspect (/Users/m/Workspace/cequens/agc/ChatApps-agc-server/node_modules/mongoose/lib/document.js:3482:20)
    at formatValue (internal/util/inspect.js:491:31)
    at inspect (internal/util/inspect.js:189:10)
    at Object.formatWithOptions (util.js:84:12)
    at Console.(anonymous function) (console.js:191:15)
    at Console.log (console.js:202:31)`
