### ISSUE TITLE
Cannot connect to MongoDB

### ISSUE THREAD

**Issue by bfharreguy** [Tiledesk/tiledesk-server#38]
I cannot connect to the DB, I try to run auth=true, with user and pass Here the code:

```
Listening tiledesk-server ver:2.1.0-beta.21 on port 3001
error: Failed to connect to MongoDB on mongodb://admin:Contrasenia123456@localhost:27017/tildesk failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] {"name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/topologies/server.js:433:11)\n    at Pool.emit (events.js:198:13)\n    at createConnection (/usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:577:14)\n    at connect (/usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:1007:11)\n    at makeConnection (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:31:7)\n    at callback (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:247:5)\n    at Socket.err (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:276:7)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
```

Anyone knows what's

**Comment by andrealeo83** [comment]
is MongoDB running on localhost?
