### ISSUE TITLE
Facing issue when tiledesk server connect to mongo db

### ISSUE THREAD

**Issue by shikhil-gupta** [Tiledesk/tiledesk-server#94]
tiledesk-server  | (node:25) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
tiledesk-server  | (Use `node --trace-warnings ...` to show where the warning was created)
tiledesk-server  | (node:25) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
tiledesk-server  | (node:25) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
tiledesk-server  | Listening tiledesk-server ver:2.4.3 on port 3000
tiledesk-server  | error: Failed to connect to MongoDB on mongodb://mongo/tiledesk  failed to connect to server [mongo:27017] on first connect [MongoNetworkTimeoutError: connection timed out
tiledesk-server  |     at connectionFailureError (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:362:14)
tiledesk-server  |     at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:330:16)
tiledesk-server  |     at Object.onceWrapper (node:events:627:28)
tiledesk-server  |     at Socket.emit (node:events:513:28)
tiledesk-server  |     at Socket._onTimeout (node:net:550:8)
tiledesk-server  |     at listOnTimeout (node:internal/timers:559:17)
tiledesk-server  |     at processTimers (node:internal/timers:502:7)] {"name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkTimeoutError: connection timed out\n    at connectionFailureError (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:362:14)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:330:16)\n    at Object.onceWrapper (node:events:627:28)\n    at Socket.emit (node:events:513:28)\n    at Socket._onTimeout (node:net:550:8)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)]\n    at Pool.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/topologies/server.js:441:11)\n    at Pool.emit (node:events:513:28)\n    at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:564:14\n    at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:1000:11\n    at /usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:32:7\n    at callback (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:300:5)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:330:7)\n    at Object.onceWrapper (node:events:627:28)\n    at Socket.emit (node:events:513:28)\n    at Socket._onTimeout (node:net:550:8)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)"}

**Comment by sponzillo** [comment]
Please be more clear in your error description.

What distribution are you using?
Where are you installing/trying the Tiledesk software stack?
Did you modify the original stack components? 

Please follow our community guidelines:

https://developer.tiledesk.com/support#i-need-help-but-its-not-so-urgent

**Comment by gab-95** [comment]
Hi @shikhil-gupta!!
Just one question: have you an arm64 ( apple chip) processor?

**Comment by shikhil-gupta** [comment]
Do you need this?
[
<img width="256" alt="Screenshot 2023-04-27 at 10 44 18 PM" src="https://user-images.githubusercontent.com/3445254/234939187-2e701b38-3371-4926-8ff7-19c0f9738fce.png">

**Comment by gab-95** [comment]
Hi @shikhil-gupta!
unfortunately arm64 processors are not supported by tiledesk yet. we're working on it .

the valid alternative could be to use helm ( https://github.com/Tiledesk/tiledesk/blob/master/helm/README.md )

**Comment by shikhil-gupta** [comment]
Hi @gab-95 I have tried Kubernetes and Helm, facing same issue that tiledesk-server pod is failed to connect with mongodb pod.

**Comment by shikhil-gupta** [comment]
HI @gab-95 Could you please respond on why I am facing same issue with helm deployment also?
